spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: pxy736499
mybatis:
   mapperLocations: classpath:/mapper/*.xml
